.\" Manpage for Terminology
.TH man 1 "23 August 2014" "0.7" "Terminology man page"
.SH NAME
Terminology \- Terminal Emulator written with EFL (Enlightenment Foundation Libraries).
.SH SYNOPSIS
.B terminology [options]
.SH DESCRIPTION
This is an EFL terminal emulator with some extra bells and whistles.
It has many features including split terminal support, support for tabs, preview
icons for files and so on...
.SH OPTIONS
.
.TP
.B \-e, \-\-exec <cmnd>
Specify command to execute.
Defaults to \fB$SHELL\fP (or passwd shell or \fB/bin/sh\fP)
When used along with \fB\-S\fP/\fB\-\-split\fP, each argument is used as a command for a
split, leaving away the extra arguments.
With 3 splits, one vertical, a command on the right, an horizontal split on
the left with only a command on the bottom, the following arguments should be used:
\fB\-\-split v\-h\-\- \-e command1 $SHELL command2\fP
.
.TP
.B \-d=CURRENT-DIRECTORY, \-\-current\-directory=CURRENT-DIRECTORY
Change to directory for execution of terminal command.
Type: STR.
.
.TP
.B \-t=THEME, \-\-theme=THEME
Use the named edje theme or path to theme file.
Type: STR.
.
.TP
.B \-b=BACKGROUND, \-\-background=BACKGROUND
Use the named file as a background wallpaper for terminology.
Type: STR.
.
.TP
.B \-g=GEOMETRY, \-\-geometry=GEOMETRY
Terminal geometry to use (eg \fB80x24\fP or \fB80x24+50+20\fP etc.).
Type: STR.
.
.TP
.B \-n=NAME, \-\-name=NAME
Set window name.
Type: STR.
.
.TP
.B \-r=ROLE, \-\-role=ROLE
Set window role.
Type: STR.
.
.TP
.B \-s=vh\-, \-\-split=vh\-
Terminology can start with splits opened as described below.
The arguments are a string with the following characters:
 \fB\-s v\fP splits terminal vertically
 \fB\-s h\fP splits horizontally
 \fB\-\fP defines a placeholder for a shell or a command when used with
 \fB\-\-exec\fP/\fB\-e\fP
 Examples:
                      ______
                      |  |  |
 $ \fBterminology -s v\fP   |__|__|

                      ______
                      |_____|
 $ \fBterminology -s h\fP   |_____|

                       ______
                       |__|  |
 $ \fBterminology -s vh\fP   |__|__|

                       ______
                       |  |__|
 $ \fBterminology -s v-h\fP  |__|__|

                         ______
 $ \fBterminology -s vh--h\fP  |__|__|
                  \fBhv--v\fP  |__|__|
 Type: STR.
.
.TP
.B \-T=TITLE, \-\-title=TITLE
Set window title.
Type: STR.
.
.TP
.B \-i=ICON\-NAME, \-\-icon-name=ICON\-NAME
Set icon name.
Type: STR.
.
.TP
.B \-f=FONT, \-\-font=FONT
Set font (NAME/SIZE for scalable, NAME for bitmap.
Type: STR.
.
.TP
.B \-v=VIDEO\-MODULE, \-\-video-module=VIDEO\-MODULE
Set emotion module to use. Choices are: \fBauto\fP, \fBgstreamer\fP,
\fBxine\fP, \fBgeneric\fP.
.
.TP
.B \-l=LOGIN, \-\-login=LOGIN
Run the shell as a login shell.
Type: BOOL.
.
.TP
.B \-m=VIDEO\-MUTE, \-\-video-mute=VIDEO\-MUTE
Set mute mode for video playback.
Type: BOOL.
.
.TP
.B \-c=CURSOR\-BLINK, \-\-cursor-blink=CURSOR\-BLINK
Set cursor blink mode.
Type: BOOL.
.
.TP
.B \-G=VISUAL\-BELL, \-\-visual\-bell=VISUAL\-BELL
Set visual bell mode.
Type: BOOL.
.
.TP
.B \-F, \-\-fullscreen
Go into the fullscreen mode from start.
.
.TP
.B \-I, \-\-iconic
Go into an iconic state from the start.
.
.TP
.B \-B, \-\-borderless
Become a borderless managed window.
.
.TP
.B \-O, \-\-override
Become an override-redirect window.
.
.TP
.B \-M, \-\-maximized
Become maximized from the start.
.
.TP
.B \-W, \-\-nowm
Terminology is run without a wm.
.
.TP
.B \-H, \-\-hold
Don't exit when the command process exits.
.
.TP
.B \-s, \-\-single
Force single executable if multi-instance is enabled..
.
.TP
.B \-2, \-\-256color
Set TERM to \fBxterm-256color\fP instead of \fBxterm\fP.
.
.TP
.B \-\-active\-links=ACTIVATE\-LINKS
Whether to highlight links.
Type: BOOL.
.
.TP
.B \-V, \-\-version
Show program version.
.
.TP
.B \-C, \-\-copyright
Show copyright.
.
.TP
.B \-L, \-\-license
Show license.
.
.TP
.B \-h, \-\-help
Show this message.

.SH CONTROLS / SHORTCUTS
.
.TP
.B Shift+PgUp
Scroll terminology one page up
.
.TP
.B Shift+PgDn
Scroll terminology one page down
.
.TP
.B Shift+Up
Scroll terminology one line up
.
.TP
.B Shift+Down
Scroll terminology one line down
.
.TP
.B Shift+Insert
Paste Clipboard (ctrl+v/c) selection
.
.TP
.B Shift+Ctrl+Insert
Paste Primary (highlight) selection
.
.TP
.B Shift+Keypad\-Plus
Font size up by one unit.
.
.TP
.B Shift+Keypad\-Minus
Font size down by one unit.
.
.TP
.B Shift+Keypad\-Multiply
Reset font size.
.
.TP
.B Shift+Keypad\-Divide
Copy highlight to Clipboard (same as ctrl+c in gui apps).
.
.TP
.B Ctrl+PgUp
Switch focus to previous terminal inside a window (when using splits).
.
.TP
.B Ctrl+PgDn
Switch focus to next terminal inside a window (when using splits).
.
.TP
.B Ctrl+Shift+h
Toggle displaying the miniview of the history.
.
.TP
.B Ctrl+Shift+t
Create a new terminal on top of current inside window (tabs).
.
.TP
.B Ctrl+Shift+Home
Bring up "tab" switcher.
.
.TP
.B Ctrl+Shift+PgUp
Split terminal horizontally (one terminal above the other).
.
.TP
.B Ctrl+Shift+PgDn
Split terminal vertically (one terminal to the left of the other).
.
.TP
.B Alt+Home
Enter command mode (enter commands to control terminology itself)
.
.TP
.B Alt+Return
Paste primary selection.
.
.TP
.B Alt+w
Copy selection to primary.
.
.TP
.B Ctrl+Shift+c
Copy current selection to clipboard.
.
.TP
.B Ctrl+Shift+v
Paste current clipboard selection.
.
.TP
.B Ctrl+1 through Ctrl+0
Switch to terminal tab 1 through 10
.
.TP
.B Ctrl+Alt+Equal
Increase font size. Note that it works on scalable fonts only.
.
.TP
.B Ctrl+Alt+Minus
Decrease font size. Note that it works on scalable fonts only.
.
.TP
.B Ctrl+Alt+0
Reset font to default setting saved in config.
.
.TP
.B Ctrl+Alt+9
Display big font size (10x20 bitmap, or size 20 with scalable).

.SH MOUSE CONTROLS
.
.TP
.B Right mouse click
Bring up controls menus.
.
.TP
.B Middle mouse click
Paste highlight selection.
.
.TP
.B Left mouse click/drag
Make a selection highlight.
.
.TP
.B Ctrl + Left mouse click/drag
Make a block selection.
.
.TP
.B Wheel
Scroll up or down in history.
.
.TP
.B Ctrl + Wheel
Zoom font size up/down.

.SH COMMAND MODE COMMANDS
To enter command mode in terminology press Alt+Home. Currently command mode
understands the following commands:
.
.TP
.B f
Reset font to default setting saved in config.
.
.TP
.B f+
Increase font size. Note that it works on scalable fonts only.
.
.TP
.B f\-
Decrease font size. Note that it works on scalable fonts only.
.
.TP
.B fb
Display big font size (10x20 bitmap, or size 20 with scalable).
.
.TP
.B gNxM
Make terminal NxM chars in size (if possible). e.g. \fBg80x48\fP \fBg40x20\fP.
If just one number is provided, it will use the following shortcuts:
\fBg0=80x24\fP; \fBg1=80x40\fP; \fBg2=80x60\fP; \fBg3=80x80\fP;
\fBg4=120x24\fP; \fBg5=120x40\fP; \fBg6=120x60\fP;
\fBg7=120x80\fP; \fBg8=120x120\fP
.
.TP
.B b
Reset the background (no media)
.
.TP
.B bPATH
Set the background media to an absolute file PATH

.SH THEMES:
Themes can be stored in \fB~/.config/terminology/themes/\fP .


.SH EXTENDED ESCAPES FOR TERMINOLOGY:
.
.TP
.B [\\\033][}][COMMAND][\\\000]
i.e.
  1.   ESC char (\fB\\033\fP or \fB0x1b\fP)
  2.   \fB}\fP char
  3... sequence of UTF8 chars other than nul (\fB\\000\fP or \fB0x00\fP).
  4    \fB\\000\fP char (nul byte or \fB0x00\fP to indicate end of sequence)
e.g.
  \fBecho \-n '\\033}Hello world\\000'\fP

.B Commands:

any values inside square brackets [] are to be replaced by some content (numbers, strings, paths, url's etc.). example:

\fBaa[PATH\-OF\-FILE]\fP should be come something like:
  \fBaa/tmp/file.png\fP
or \fBaa[true/false]\fP should become something like:
  \fBaatrue\fP
or
  \fBaafalse\fP

\-\-\-

\fBpn[FULL\-PATH\-OR\-URL]\fP
  popup the given media file/url now

\fBpq[FULL\-PATH\-OR\-URL]\fP
  quque a popup for the given media file/url

\fBbt[FULL\-PATH\-OR\-URL]\fP
  set the terminal background media file/url temporarily

\fBbp[FULL\-PATH\-OR\-URL]\fP
  set the terminal background media file/url permanently

\fBat[on/true/yes/off/false/no]\fP
  set the terminal alpha state to be on, or off temporarily

\fBap[on/true/yes/off/false/no]\fP
  set the terminal alpha state to be on, or off permanently

\fBqs\fP
  query grid and font size. stdin will have written to it:
    \fBW;H;FW;FH\fP
  where \fBW\fP is the width of the terminal grid in characters
  where \fBH\fP is the height of the terminal grid in characters
  where \fBFW\fP is the width of 1 character cell in pixels
  where \fBFH\fP is the height of 1 character cell in pixels

\fBis[CW;H;FULL\-PATH\-OR\-URL]\fP
  insert STRETCHED media (where image will stretch to fill the
    cell area) and define expected cell area to be \fBW\fP cells
    wide and \fBH\fP cells high, with the image/media/url.
  where \fBC\fP is the replace character to be identified in later
    text where \fBW\fP is the width in character cells (up to 511).
  where \fBH\fP is the height in character cells (up to 511).

  note that this escape alone has no effect. it indicates a future intention of inserting media into the terminal. the terminal will EXPECT a grid of \fBW\fPx\fBH\fP "replace characters" to follow, with each sequence of such replace characters bebung with a \fBib\fP escape command and ending with an \fBie\fP escape command.

  the \fBFULL\-PATH\-OR\-URL\fP for all  the \fBi\fP commands (\fBis\fP,
  \fBic\fP, \fBif\fP, \fBit\fP) may be of the form:

    \fB/full/path/to/file.png\fP

  OR

    \fB/full/path/to/link\n/full/path/to/file.png\fP

    where a newline character separates a URI for a link and
      a full path to a file to display in the region. the link
      is the destination URI when a user may clikc on the given
      media image.

    example:

      \fBprintf("\\\033}is#5;3;%s\000"\fP
             \fB"\\\033}ib#####\\\033}ie\\\n"\fP
             \fB"\\\033}ib#####\\\033}ie\\\n"\fP
             \fB"\\\033}ib#####\\\033}ie\\\n", "/tmp/icon.png");\fP

    note that \fB#\fP is the replace character, and later \fB#\fP chars if inside begin/end escapes, will be replaced by the given media indicated in the insert media escape.

\fBic[CW;H;FULL\-PATH\-OR\-URL]\fP
  insert CENTERED media (centered in cell area). otherwise
    paramaters are identical to the \fBis\fP command, but
    retains aspect and is padded by blank space.

\fBif[CW;H;FULL\-PATH\-OR\-URL]\fP
  insert FILLED media (fill in cell area). otherwise paramaters
    are identical to the \fBis\fP command but ensures the entire
    area is filled like a background even if media goes beyond
    cell bounds and is clipped.

\fBit[CW;H;FULL\-PATH\-OR\-URL]\fP
  insert THUMB media (thumbnail cell area). otherwise paramaters
    are identical to the \fBis\fP command, but uses thumbnail
    generation to make a fast to load but low resolution version
    (cached) of the media.

\fBib\fP
  begin media replace sequence run

\fBie\fP
  end media replace sequence run

.SH BUGS
If you find a bug or for known issues/bugs/feature requests please email enlightenment-devel@lists.sourceforge.net or visit the place where all the hard work is done http://phab.enlightenment.org/

.SH AUTHOR
Terminology was written by Carsten Haitzler <raster@rasterman.com> and others. See AUTHORS file for other contributors.
